### ISSUE TITLE
Installed mod but doesn't work for me

### ISSUE THREAD

**Issue by BinaryVigilante** [cloewen8/Snowed-In#1]
Hi,

I installed the mod on Minecraft 1.16.5 Fabric but it doesn't work. I log in a newly generated world and nothing happens. Mod Menu does detect the mod and the gamerule of snow pilling gets seen by Minecraft but nothing happens, not even when I force rain on using commands.

Using Minecraft 1.16.5 and running Fabric Loader 0.11.3.

Best Regards!

**Comment by cloewen8** [comment]
Thank you for reporting this. I confirmed the bug on my end and will be looking into a fix.

In the mean time. I believe this may be an incompatibility with Minecraft 1.16.5. The mod was originally designed for version 1.16.4 which should still work.

**Comment by BinaryVigilante** [comment]
Hmm, I tried it in 1.16.4 but it still didn't work, Mod Menu would detect it and the gamerule is also there but it doesn't snow nor does the water freeze. I tried removing any other mods and it still didn't work, I also tried a different Fabric version (I tried 0.11.3 & 0.11.2)

**Comment by cloewen8** [comment]
Thank you for the help. I am actively working on this bug and will let you know if I have any updates.

**Comment by BinaryVigilante** [comment]
Nice, let me know if I can provide further information.

**Comment by cloewen8** [comment]
Sorry for the delay, found a solution that works on my end. Please give it a try and make sure it works for you:
https://github.com/cloewen8/Snowed-In/releases/tag/v1.0.3

**Comment by BinaryVigilante** [comment]
I can confirm it is now working! So weird to see snow in the desert 😂 - Thanks for making this amazing mod and for fixing this issue!

**Comment by cloewen8** [comment]
Thank you for trying my mod and sticking through the bug fixing process! I am glad you are enjoying it now. If you notice any other bugs, please create a new issue and I'll investigate right away.
